CREATE TABLE AUTHORITY(
  ID SMALLINT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR2(20)
);

CREATE TABLE USER(
  ID BIGINT AUTO_INCREMENT NOT NULL,
  USERNAME VARCHAR2(30) UNIQUE NOT NULL,
  EMAIL VARCHAR2(30) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(255) NOT NULL,
  FIRSTNAME VARCHAR2(20) NOT NULL,
  LASTNAME VARCHAR2(20) NOT NULL,
  ENABLED BOOLEAN NOT NULL
);

CREATE TABLE USER_AUTHORITY(
  USER_ID BIGINT NOT NULL,
  AUTHORITY_ID SMALLINT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY(ID)
);