CREATE TABLE AUTHORITIES(
  ID SMALLINT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR2(20)
);

CREATE TABLE USERS(
  ID BIGINT AUTO_INCREMENT NOT NULL,
  USERNAME VARCHAR2(30) UNIQUE NOT NULL,
  EMAIL VARCHAR2(30) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(255) NOT NULL,
  FIRSTNAME VARCHAR2(20) NOT NULL,
  LASTNAME VARCHAR2(20) NOT NULL,
  ENABLED BOOLEAN NOT NULL
);

CREATE TABLE USERS_AUTHORITIES(
  USER_ID BIGINT NOT NULL,
  AUTHORITY_ID SMALLINT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITIES(ID)
);

CREATE TABLE DEPARTMENTS(
  ID SMALLINT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR2(50)
);

CREATE TABLE BRANDS(
  ID SMALLINT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR2(30)
);

CREATE TABLE ITEMS(
  ID BIGINT AUTO_INCREMENT NOT NULL,
  PRICE FLOAT NOT NULL,
  DESCRIPTION VARCHAR2(50),
  MODEL VARCHAR2(30) NOT NULL,
  COLOR VARCHAR2(20) NOT NULL,
  BRAND_ID SMALLINT NOT NULL,
  DEPARTMENT_ID SMALLINT NOT NULL,
  FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)
);
